#!/usr/bin/env python3
"""Generate one static per-list page per entry in data/lists/index.json.

Usage (from repo root):  python3 scripts/generate-list-pages.py

Why this exists: frontend/navras/pages/list.html is one shared template
loaded via ?slug=<slug> for all 21+ lists. Its <title> and
<meta name="description"> are hardcoded to one generic line, and only the
title is ever corrected — by client-side JS, after a fetch resolves. That
means every list looks identical to anything that reads the raw HTML
response before JS runs: search crawlers on first pass, and link-preview
bots (Slack, WhatsApp, Twitter), which never run JS at all.

This script writes frontend/navras/pages/list-<slug>.html for every list —
list.html copied verbatim except <title>, <meta name="description">, a
self-referencing <link rel="canonical">, and a data-slug attribute on
#listRoot so js/list.js knows which list to fetch without a query string.
#listRoot itself is untouched: film rows still come from the existing
list.js -> data/lists/<slug>.json -> TMDb pipeline. Real server-rendered
rows would need a framework this codebase doesn't have; correct title and
meta description, present without JS, is the part that's actually
achievable here — so that's the part this generates.

Re-run this whenever a list is added, renamed, or its description
changes, and commit the output — there's no CI step for this yet.
"""
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
NAVRAS_DIR = REPO_ROOT / "frontend" / "navras"
INDEX_PATH = NAVRAS_DIR / "data" / "lists" / "index.json"
TEMPLATE_PATH = NAVRAS_DIR / "pages" / "list.html"
OUT_DIR = NAVRAS_DIR / "pages"

GENERATED_MARKER = (
    "  <!-- Generated by scripts/generate-list-pages.py from data/lists/index.json.\n"
    "       Don't hand-edit — re-run the script after changing this list's title,\n"
    "       description, or slug, and commit the result. -->\n"
)


def escape_html(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def escape_attr(s: str) -> str:
    return escape_html(s).replace('"', "&quot;")


def build_page(template: str, entry: dict) -> str:
    slug = entry["slug"]
    title = entry.get("title") or slug
    description = entry.get("description") or ""

    page = template

    # <title>CineRaaga List</title> -> <title>{real title} | CineRaaga</title>
    old_title = "<title>CineRaaga List</title>"
    new_title = f"<title>{escape_html(title)} | CineRaaga</title>"
    if old_title not in page:
        sys.exit(f"list.html template drifted — expected {old_title!r}, not found")
    page = page.replace(old_title, new_title, 1)

    # Generic <meta description> -> this list's real one, plus a
    # self-referencing canonical tag right after it.
    old_meta = (
        '<meta name="description" content="A hand-ranked CineRaaga list '
        'of Indian films — curated, not algorithmic." />'
    )
    if old_meta not in page:
        sys.exit(f"list.html template drifted — expected the generic <meta description>, not found")
    new_meta = (
        f'<meta name="description" content="{escape_attr(description)}" />\n'
        f'  <link rel="canonical" href="list-{escape_attr(slug)}.html" />'
    )
    page = page.replace(old_meta, new_meta, 1)

    # #listRoot carries the slug so list.js doesn't need ?slug= at all.
    old_root = '<div id="listRoot"></div>'
    new_root = f'<div id="listRoot" data-slug="{escape_attr(slug)}"></div>'
    if old_root not in page:
        sys.exit(f"list.html template drifted — expected {old_root!r}, not found")
    page = page.replace(old_root, new_root, 1)

    # Mark the file as generated, right after <head>.
    page = page.replace("<head>\n", "<head>\n" + GENERATED_MARKER, 1)

    return page


def main() -> None:
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    slugs_seen = set()
    written = []
    for entry in index:
        slug = entry["slug"]
        if slug in slugs_seen:
            sys.exit(f"duplicate slug in index.json: {slug}")
        slugs_seen.add(slug)

        page = build_page(template, entry)
        out_path = OUT_DIR / f"list-{slug}.html"
        out_path.write_text(page, encoding="utf-8")
        written.append(out_path.relative_to(REPO_ROOT))

    print(f"Wrote {len(written)} pages:")
    for p in written:
        print(f"  {p}")


if __name__ == "__main__":
    main()
